# -*- coding: utf-8 -*-
"""install

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFjbF_AGpTZY3ucMyE1-6iHoilmRLPBk
"""

!pip install fastbook

import fastbook
fastbook.setup_book()

from fastbook import *