# -*- coding: utf-8 -*-
"""Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0lNGssUQvDbH1oShHxzdB1xzvvqEeKR
"""

[theme]
base="dark"
backgroundColor="#253342"
font="serif"